first_num = input("Write the first number\n")
second_num = input("Write the second number\n")
total_num = int(first_num) + int(second_num)
t_num = str(total_num)
print("The sum of the number is " + t_num)
